name: CI

on:
  push:
    branches:
      - main

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r microservices/service1/requirements.txt
          pip install --no-cache-dir -r microservices/service2/requirements.txt
          pip install flake8
          pip install pytest

      - name: Run flake8
        run: |
          flake8 microservices/service1
          flake8 microservices/service2

      - name: Run tests with the script test.sh
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh

